### ISSUE TITLE
Shared SDIO+fatfs

### ISSUE THREAD

**Issue by EniacMlezi** [akospasztor/stm32-bootloader#1]
The Bootloader currently uses SDIO+fatfs to read the new firmware file. If I want to use SDIO+fatfs in application code, it will be in memory twice. Is there a way to share the SDIO+fatfs through some clever linking?

**Comment by LarsGardien** [comment]
The Bootloader currently uses SDIO+fatfs to read the new firmware file. If I want to use SDIO+fatfs in application code, it will be in memory twice. Is there a way to share the SIO+fatfs through some clever linking?

**Comment by akospasztor** [comment]
This is actually a good point, but I haven't tried it yet though. My guess is that you have to compile the SDIO+FatFs as a library (instead of an executable) and link the library to both projects (the bootloader and the application). However both projects somehow need to 'know' that they use the same library so there is no need to load the library twice into the flash. 
However, this method triggers some problems, especially when you want to upgrade the shared library. As someone pointed out: "You cannot have your cake and eat it." Please see the answers here:
https://stackoverflow.com/questions/17248266/bootloader-and-firmware-common-usage-and-firmware-upgrade
