### ISSUE TITLE
stm32-bootloader for stm32f103xxxx series

### ISSUE THREAD

**Issue by sankaramp** [akospasztor/stm32-bootloader#5]
hello akospasztor,

first of all thanks for ur driver.
my application is also same as ur application but for stm32f103xxxx series.
 
can u suggest in writing this driver for my controlller....please...

thanks,
sankar

**Comment by akospasztor** [comment]
Hi Sankar,

 

If you’re planning to use the HAL libraries from ST, then porting should be really simple. Porting to Cortex-M3 core MCUs, like the F103xx series is really simple, as the architecture is really similar to the M4 architecture. Of course, it depends on how much you know those processors and their specifications. If you consider not to use the HAL libraries, then it is a bit more complicated, because you have to fully understand what is going on “under the hood”. 

 

I suggest to start diving into my code and try to understand it first. Then the most important document you need to dive into is the reference manual (RMxxx) of your specific microcontroller, especially the chapters that describe the operation and the organization of the internal flash. 

 

I hope I could provide some starting points for you, and don’t hesitate to contact me if you have further questions.

 

Best,

 

Akos Pasztor

 <mailto:mail@akospasztor.com> mail@akospasztor.com

 <https://akospasztor.com> https://akospasztor.com

**Comment by Rotule666** [comment]
Hello sankar,

I ported it to F373 and it was pretty easy, most of the functions worked right out but I had to change memory functions to work with a single bank memory. (I think you will have to do this too) but it's pretty simple if you read the datasheet.

I also changed everything to load the app from CAN instead of UART.

Cheers.

Francois

**Comment by sankaramp** [comment]
thanq so much for quick replies,

i got some idea about that i'll go through that RM0008 user manual.
but i'm using Arduino IDE and     https://github.com/rogerclarkmelbourne/Arduino_STM32       this hardware libraries for my coding...
if u give advice related to those,it will be very helpful for me..

thanq,
sankar

**Comment by akospasztor** [comment]
Hi Sankar,

let me give you a friendly advice. If you want to develop serious and robust embedded applications, I would recommend to "get your hands dirty" and ditch those libraries. The biggest problems with those libraries (apart from that they are not quite reliable) is that they hide the underlying hardware from the developer, thus preventing the implementation of well-written, optimized and robust code. I would suggest to get a little bit familiar with the core and the peripherals, and how they actually work on register-level. I know it seems a lot of investment at first, but it has countless benefits on the long run.

Even the HAL libraries from ST are only good for prototyping purposes. I use custom, low-level implementations in my work-related projects to ensure optimized, safe and robust operation. The reason is why I decided to publish this project here with HAL libraries is to make it better understandable (thus easier to port) for the community. 

Best,
Akos

**Comment by sankaramp** [comment]
Thanq so much sir,,, I'll try to implement about what u said...
