### ISSUE TITLE
OTA firmware update on stm8s

### ISSUE THREAD

**Issue by mdjunaidahmed0123** [akospasztor/stm32-bootloader#56]
@akospasztor Is there any solution for updating firmware wirelessly (OTA) on stm8s003f3p6 chip ?

**Comment by akospasztor** [comment]
Hi mdjunaidahmed0123,

Of course! The general principle is (almost) the same: you need to check for a new firmware image via your wireless connection. If there is a new firmware, you need to transfer the new image to the device and save it to either a reserved space in your microcontroller or to an external storage (eeprom, flash, etc..). Then you need to launch the bootloader and if everything checks out, replace the old application firmware with the new application image. 

Everything boils down how much resources the MCU has, what kind of storage you've foreseen to store the new app image and what kind of communication interfaces you want to utilize. Performing OTA updates, you will want to write a robust code so that e.g. when the wireless connection randomly drops out during the reception of the new application image, you still would want to automatically recover and continue the reception after the wireless signal/service is restored.

Best,
Akos
